// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { Timestamp } from "../../google/protobuf/Timestamp";

export class Pimeth_PiNftBurnt {
  static encode(message: Pimeth_PiNftBurnt, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.evtTxHash);

    writer.uint32(16);
    writer.uint32(message.evtIndex);

    const evtBlockTime = message.evtBlockTime;
    if (evtBlockTime !== null) {
      writer.uint32(26);
      writer.fork();
      Timestamp.encode(evtBlockTime, writer);
      writer.ldelim();
    }

    writer.uint32(32);
    writer.uint64(message.evtBlockNumber);

    writer.uint32(42);
    writer.bytes(message.collectionAddress);

    writer.uint32(50);
    writer.string(message.tokenId);

    writer.uint32(58);
    writer.bytes(message.nftReciever);

    writer.uint32(66);
    writer.bytes(message.erc20Receiver);

    writer.uint32(74);
    writer.bytes(message.erc20Contract);

    writer.uint32(82);
    writer.string(message.value);
  }

  static decode(reader: Reader, length: i32): Pimeth_PiNftBurnt {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Pimeth_PiNftBurnt();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.evtTxHash = reader.string();
          break;

        case 2:
          message.evtIndex = reader.uint32();
          break;

        case 3:
          message.evtBlockTime = Timestamp.decode(reader, reader.uint32());
          break;

        case 4:
          message.evtBlockNumber = reader.uint64();
          break;

        case 5:
          message.collectionAddress = reader.bytes();
          break;

        case 6:
          message.tokenId = reader.string();
          break;

        case 7:
          message.nftReciever = reader.bytes();
          break;

        case 8:
          message.erc20Receiver = reader.bytes();
          break;

        case 9:
          message.erc20Contract = reader.bytes();
          break;

        case 10:
          message.value = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  evtTxHash: string;
  evtIndex: u32;
  evtBlockTime: Timestamp | null;
  evtBlockNumber: u64;
  collectionAddress: Uint8Array;
  tokenId: string;
  nftReciever: Uint8Array;
  erc20Receiver: Uint8Array;
  erc20Contract: Uint8Array;
  value: string;

  constructor(
    evtTxHash: string = "",
    evtIndex: u32 = 0,
    evtBlockTime: Timestamp | null = null,
    evtBlockNumber: u64 = 0,
    collectionAddress: Uint8Array = new Uint8Array(0),
    tokenId: string = "",
    nftReciever: Uint8Array = new Uint8Array(0),
    erc20Receiver: Uint8Array = new Uint8Array(0),
    erc20Contract: Uint8Array = new Uint8Array(0),
    value: string = ""
  ) {
    this.evtTxHash = evtTxHash;
    this.evtIndex = evtIndex;
    this.evtBlockTime = evtBlockTime;
    this.evtBlockNumber = evtBlockNumber;
    this.collectionAddress = collectionAddress;
    this.tokenId = tokenId;
    this.nftReciever = nftReciever;
    this.erc20Receiver = erc20Receiver;
    this.erc20Contract = erc20Contract;
    this.value = value;
  }
}
