// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { Timestamp } from "../../google/protobuf/Timestamp";

export class Pimeth_RedeemOrBurnPiNftCall {
  static encode(message: Pimeth_RedeemOrBurnPiNftCall, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.callTxHash);

    const callBlockTime = message.callBlockTime;
    if (callBlockTime !== null) {
      writer.uint32(18);
      writer.fork();
      Timestamp.encode(callBlockTime, writer);
      writer.ldelim();
    }

    writer.uint32(24);
    writer.uint64(message.callBlockNumber);

    writer.uint32(32);
    writer.uint64(message.callOrdinal);

    writer.uint32(40);
    writer.bool(message.callSuccess);

    writer.uint32(50);
    writer.bytes(message.uCollectionAddress);

    writer.uint32(58);
    writer.string(message.uTokenId);

    writer.uint32(66);
    writer.bytes(message.uNftReceiver);

    writer.uint32(74);
    writer.bytes(message.uErc20Receiver);

    writer.uint32(82);
    writer.bytes(message.uErc20Contract);

    writer.uint32(88);
    writer.bool(message.burnNft);
  }

  static decode(reader: Reader, length: i32): Pimeth_RedeemOrBurnPiNftCall {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Pimeth_RedeemOrBurnPiNftCall();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.callTxHash = reader.string();
          break;

        case 2:
          message.callBlockTime = Timestamp.decode(reader, reader.uint32());
          break;

        case 3:
          message.callBlockNumber = reader.uint64();
          break;

        case 4:
          message.callOrdinal = reader.uint64();
          break;

        case 5:
          message.callSuccess = reader.bool();
          break;

        case 6:
          message.uCollectionAddress = reader.bytes();
          break;

        case 7:
          message.uTokenId = reader.string();
          break;

        case 8:
          message.uNftReceiver = reader.bytes();
          break;

        case 9:
          message.uErc20Receiver = reader.bytes();
          break;

        case 10:
          message.uErc20Contract = reader.bytes();
          break;

        case 11:
          message.burnNft = reader.bool();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  callTxHash: string;
  callBlockTime: Timestamp | null;
  callBlockNumber: u64;
  callOrdinal: u64;
  callSuccess: bool;
  uCollectionAddress: Uint8Array;
  uTokenId: string;
  uNftReceiver: Uint8Array;
  uErc20Receiver: Uint8Array;
  uErc20Contract: Uint8Array;
  burnNft: bool;

  constructor(
    callTxHash: string = "",
    callBlockTime: Timestamp | null = null,
    callBlockNumber: u64 = 0,
    callOrdinal: u64 = 0,
    callSuccess: bool = false,
    uCollectionAddress: Uint8Array = new Uint8Array(0),
    uTokenId: string = "",
    uNftReceiver: Uint8Array = new Uint8Array(0),
    uErc20Receiver: Uint8Array = new Uint8Array(0),
    uErc20Contract: Uint8Array = new Uint8Array(0),
    burnNft: bool = false
  ) {
    this.callTxHash = callTxHash;
    this.callBlockTime = callBlockTime;
    this.callBlockNumber = callBlockNumber;
    this.callOrdinal = callOrdinal;
    this.callSuccess = callSuccess;
    this.uCollectionAddress = uCollectionAddress;
    this.uTokenId = uTokenId;
    this.uNftReceiver = uNftReceiver;
    this.uErc20Receiver = uErc20Receiver;
    this.uErc20Contract = uErc20Contract;
    this.burnNft = burnNft;
  }
}
