// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { Timestamp } from "../../google/protobuf/Timestamp";

export class Pinft_InitializeCall {
  static encode(message: Pinft_InitializeCall, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.callTxHash);

    const callBlockTime = message.callBlockTime;
    if (callBlockTime !== null) {
      writer.uint32(18);
      writer.fork();
      Timestamp.encode(callBlockTime, writer);
      writer.ldelim();
    }

    writer.uint32(24);
    writer.uint64(message.callBlockNumber);

    writer.uint32(32);
    writer.uint64(message.callOrdinal);

    writer.uint32(40);
    writer.bool(message.callSuccess);

    writer.uint32(50);
    writer.string(message.uName);

    writer.uint32(58);
    writer.string(message.uSymbol);

    writer.uint32(66);
    writer.bytes(message.uPiNftMethodsAddress);

    writer.uint32(74);
    writer.bytes(message.tfGelato);
  }

  static decode(reader: Reader, length: i32): Pinft_InitializeCall {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Pinft_InitializeCall();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.callTxHash = reader.string();
          break;

        case 2:
          message.callBlockTime = Timestamp.decode(reader, reader.uint32());
          break;

        case 3:
          message.callBlockNumber = reader.uint64();
          break;

        case 4:
          message.callOrdinal = reader.uint64();
          break;

        case 5:
          message.callSuccess = reader.bool();
          break;

        case 6:
          message.uName = reader.string();
          break;

        case 7:
          message.uSymbol = reader.string();
          break;

        case 8:
          message.uPiNftMethodsAddress = reader.bytes();
          break;

        case 9:
          message.tfGelato = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  callTxHash: string;
  callBlockTime: Timestamp | null;
  callBlockNumber: u64;
  callOrdinal: u64;
  callSuccess: bool;
  uName: string;
  uSymbol: string;
  uPiNftMethodsAddress: Uint8Array;
  tfGelato: Uint8Array;

  constructor(
    callTxHash: string = "",
    callBlockTime: Timestamp | null = null,
    callBlockNumber: u64 = 0,
    callOrdinal: u64 = 0,
    callSuccess: bool = false,
    uName: string = "",
    uSymbol: string = "",
    uPiNftMethodsAddress: Uint8Array = new Uint8Array(0),
    tfGelato: Uint8Array = new Uint8Array(0)
  ) {
    this.callTxHash = callTxHash;
    this.callBlockTime = callBlockTime;
    this.callBlockNumber = callBlockNumber;
    this.callOrdinal = callOrdinal;
    this.callSuccess = callSuccess;
    this.uName = uName;
    this.uSymbol = uSymbol;
    this.uPiNftMethodsAddress = uPiNftMethodsAddress;
    this.tfGelato = tfGelato;
  }
}
