// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.3

import { Writer, Reader } from "as-proto/assembly";
import { Timestamp } from "../../google/protobuf/Timestamp";

export class Validatednft_SafeTransferFrom1call {
  static encode(
    message: Validatednft_SafeTransferFrom1call,
    writer: Writer
  ): void {
    writer.uint32(10);
    writer.string(message.callTxHash);

    const callBlockTime = message.callBlockTime;
    if (callBlockTime !== null) {
      writer.uint32(18);
      writer.fork();
      Timestamp.encode(callBlockTime, writer);
      writer.ldelim();
    }

    writer.uint32(24);
    writer.uint64(message.callBlockNumber);

    writer.uint32(32);
    writer.uint64(message.callOrdinal);

    writer.uint32(40);
    writer.bool(message.callSuccess);

    writer.uint32(50);
    writer.bytes(message.from);

    writer.uint32(58);
    writer.bytes(message.to);

    writer.uint32(66);
    writer.string(message.tokenId);
  }

  static decode(
    reader: Reader,
    length: i32
  ): Validatednft_SafeTransferFrom1call {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Validatednft_SafeTransferFrom1call();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.callTxHash = reader.string();
          break;

        case 2:
          message.callBlockTime = Timestamp.decode(reader, reader.uint32());
          break;

        case 3:
          message.callBlockNumber = reader.uint64();
          break;

        case 4:
          message.callOrdinal = reader.uint64();
          break;

        case 5:
          message.callSuccess = reader.bool();
          break;

        case 6:
          message.from = reader.bytes();
          break;

        case 7:
          message.to = reader.bytes();
          break;

        case 8:
          message.tokenId = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  callTxHash: string;
  callBlockTime: Timestamp | null;
  callBlockNumber: u64;
  callOrdinal: u64;
  callSuccess: bool;
  from: Uint8Array;
  to: Uint8Array;
  tokenId: string;

  constructor(
    callTxHash: string = "",
    callBlockTime: Timestamp | null = null,
    callBlockNumber: u64 = 0,
    callOrdinal: u64 = 0,
    callSuccess: bool = false,
    from: Uint8Array = new Uint8Array(0),
    to: Uint8Array = new Uint8Array(0),
    tokenId: string = ""
  ) {
    this.callTxHash = callTxHash;
    this.callBlockTime = callBlockTime;
    this.callBlockNumber = callBlockNumber;
    this.callOrdinal = callOrdinal;
    this.callSuccess = callSuccess;
    this.from = from;
    this.to = to;
    this.tokenId = tokenId;
  }
}
